/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-06-08 18:58:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <title>AMS</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" >\n");
      out.write("  	<link href=\"css/Home.css\" rel=\"stylesheet\">\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("  <!-- Navbar -->\n");
      out.write("	<nav class=\"navbar navbar-expand-lg fixed-top\">\n");
      out.write("		<div class=\"container-fluid\">\n");
      out.write("			<a class=\"navbar-brand me-auto\" href=\"\">AMS</a>\n");
      out.write("			<div class=\"offcanvas offcanvas-end\" tabindex=\"-1\"\n");
      out.write("				id=\"offcanvasNavbar\" aria-labelledby=\"offcanvasNavbarLabel\">\n");
      out.write("				<div class=\"offcanvas-header\">\n");
      out.write("					<h5 class=\"offcanvas-title\" id=\"offcanvasNavbarLabel\">AMS</h5>\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\"\n");
      out.write("						aria-label=\"Close\"></button>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"offcanvas-body\">\n");
      out.write("					<ul class=\"navbar-nav justify-content-center flex-grow-1 pe-3\">\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link mx-lg-2 active\"\n");
      out.write("							aria-current=\"page\" href=\"#\">Home</a></li>\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link mx-lg-2\" href=\"#\">About</a>\n");
      out.write("						</li>\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link mx-lg-2\" href=\"#\">Services</a>\n");
      out.write("						</li>\n");
      out.write("						<li class=\"nav-item\"><a class=\"nav-link mx-lg-2\" href=\"#\">Contact</a>\n");
      out.write("						</li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<a class=\"register-button\" data-bs-toggle=\"modal\" data-bs-target=\"#register\">Register</a><br>\n");
      out.write("			<a class=\"login-button\" data-bs-toggle=\"modal\" data-bs-target=\"#login\">Login</a>\n");
      out.write("			<button class=\"navbar-toggler pe-0\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasNavbar\" aria-controls=\"offcanvasNavbar\" aria-label=\"Toggle navigation\">\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("			</button>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("	<section class=\"hero-section\">\n");
      out.write("		<div class=\"container d-flex align-items-center justify-content-center fs-1 text-white flex-column\">\n");
      out.write("			<h2>Welcome to Aadhar Management System </h2>\n");
      out.write("			<h3 >Key Features</h3>\n");
      out.write("        <ul id=\"ul\" style=\"max-width: 500px;\"> \n");
      out.write("            <li >User Registration</li>\n");
      out.write("            <li >User Authentication</li>\n");
      out.write("            <li >Data Entry and Update</li>\n");
      out.write("            <li >Data Retrieval</li>\n");
      out.write("            <li >Administrative Tools</li>\n");
      out.write("        </ul>\n");
      out.write("		</div>\n");
      out.write("	</section>\n");
      out.write("\n");
      out.write("<!-- Modal for login-->\n");
      out.write("<div class=\"modal fade\" id=\"login\" tabindex=\"-1\" aria-labelledby=\"loginModalLabel\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header\">\n");
      out.write("        <h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Login</h1>\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("      <form class=\"form-signin\">\n");
      out.write("     <div class=\"text-center\">\n");
      out.write("     	 <img class=\"mb-4\" src=\"images/login.jpg\" alt=\"\" width=\"80\" height=\"80\">\n");
      out.write("     	 <h1 class=\"h3 mb-3 font-weight-normal\">Please Login</h1>\n");
      out.write("     </div>\n");
      out.write("      \n");
      out.write("      <input type=\"hidden\" value=\"login\"  id=\"method\" name=\"method\">\n");
      out.write("	\n");
      out.write("	  <label for=\"inputEmail\" class=\"sr-only\">Email address</label>\n");
      out.write("      <input type=\"email\" id=\"lemail\" class=\"form-control\" placeholder=\"Email address\" name=\"email\"required >\n");
      out.write("      <label for=\"inputPassword\" class=\"sr-only\">Password</label>\n");
      out.write("      <input type=\"password\" id=\"lpassword\" class=\"form-control\" placeholder=\"Password\" name=\"pass\" required>\n");
      out.write("      <div class=\"checkbox mb-3\">\n");
      out.write("        <label>\n");
      out.write("          <input type=\"checkbox\" value=\"remember-me\" onclick=\"showPasswordl()\"> Show Password\n");
      out.write("        </label>\n");
      out.write("      </div>\n");
      out.write("        <!-- <div>\n");
      out.write("		<label>Login As :</label> <br> \n");
      out.write("		<select name=\"role\" id=\"roleSelect\" style=\"width: 130px\">\n");
      out.write("			<option value=\"1\">Admin</option>\n");
      out.write("			<option value=\"2\">Junior</option>\n");
      out.write("			<option value=\"3\">User</option>\n");
      out.write("		</select>\n");
      out.write("	  </div> -->\n");
      out.write("     \n");
      out.write("      <p class=\"mt-5 mb-3 text-muted\">&copy; Kaldin Solutions</p>\n");
      out.write("    </form>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-footer\">\n");
      out.write("        <button type=\"button\" class=\"btn btn-lg btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\n");
      out.write("        <button class=\"btn btn-lg btn-primary btn-block\" id=\"submit\" type=\"submit\">Login</button>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<!-- login model end -->\n");
      out.write("\n");
      out.write("<!-- Modal for register-->\n");
      out.write("<div class=\"modal fade\" id=\"register\" tabindex=\"-1\" aria-labelledby=\"loginModalLabel\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header\">\n");
      out.write("        <h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Register</h1>\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("      <form id=\"register_form\" enctype=\"multipart/form-data\">\n");
      out.write("					<div class=\"text-center\">\n");
      out.write("						<h1 class=\"h3 mb-3 font-weight-normal\">Please Register</h1>\n");
      out.write("					</div>\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("						<input type=\"hidden\" value=\"insert\" name=\"method\">\n");
      out.write("							<label for=\"firstname\">First Name</label> <input type=\"text\"\n");
      out.write("								class=\"form-control\" id=\"firstname\" name=\"fname\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"lastname\">Last Name</label> <input type=\"text\"\n");
      out.write("								class=\"form-control\" id=\"lastname\" name=\"lname\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"email\">Email</label> <input type=\"email\"\n");
      out.write("								class=\"form-control\" id=\"email\" name=\"email\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"dob\">Date Of Birth</label> <input type=\"date\"\n");
      out.write("								class=\"form-control\" id=\"dob\" name=\"dateOfBirth\">\n");
      out.write("						</div>\n");
      out.write("						<div id= \"rpassword\" class=\"form-group\">\n");
      out.write("							<label for=\"password\">Password</label> \n");
      out.write("							<input type=\"password\" class=\"form-control\" id=\"password\" name=\"pass\"> \n");
      out.write("							<input type=\"checkbox\" onclick=\"showPassword()\"> \n");
      out.write("							<label>&nbsp; Show Password</label>\n");
      out.write("						</div>\n");
      out.write("						<div id=\"rgender\" class=\"form-group\">\n");
      out.write("							<label>Gender</label><br>\n");
      out.write("							<div class=\"form-check form-check-inline\">\n");
      out.write("								<input class=\"form-check-input\" type=\"radio\" name=\"gender\" id=\"male\" value=\"male\" checked>\n");
      out.write("								<label class=\"form-check-label\" for=\"male\">Male</label>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"form-check form-check-inline\">\n");
      out.write("								<input class=\"form-check-input\" type=\"radio\" name=\"gender\" id=\"female\" value=\"female\">\n");
      out.write("							    <label class=\"form-check-label\" for=\"female\">Female</label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div id=\"menu-container\" class=\"form-group\">\n");
      out.write("							<label>Country :</label> <br> \n");
      out.write("							<select name=\"country\" style=\"width: 130px\">\n");
      out.write("								<option value=\"\" disabled selected hidden=\"hidden\">Select Country</option>\n");
      out.write("								<option selected=\"selected\">India</option>\n");
      out.write("								<option>USA</option>\n");
      out.write("								<option>US</option>\n");
      out.write("								<option>Germany</option>\n");
      out.write("							</select>&nbsp; \n");
      out.write("							<label>Register As :</label> <br> \n");
      out.write("							<select name=\"role\" style=\"width: 130px\">\n");
      out.write("								<option value=\"\" disabled selected hidden=\"hidden\">Select Role</option>\n");
      out.write("								<option value=\"3\" selected=\"selected\">User</option>\n");
      out.write("							</select>\n");
      out.write("						</div>\n");
      out.write("						<div>\n");
      out.write("							Select Image :<input type=\"file\" name=\"image\" id=\"upload_file\"\n");
      out.write("								onchange=\"getImagePreview(event)\">\n");
      out.write("						</div>\n");
      out.write("						<div id=\"preview\"></div>\n");
      out.write("						   <p class=\"mt-5 mb-3 text-muted\">&copy; Kaldin Solutions</p>\n");
      out.write("					</form>\n");
      out.write("	 	 </div>\n");
      out.write("      <div class=\"modal-footer\">\n");
      out.write("        <button type=\"button\" class=\"btn btn-lg btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\n");
      out.write("        <button class=\"btn btn-lg btn-success btn-block\" id=\"register_form_submit\"  type=\"submit\">Register</button>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("	<script type=\"text/javascript\">var contextPath = '");
      out.print(request.getContextPath());
      out.write("'; </script>\n");
      out.write("	<script type=\"text/javascript\" src=\"javascript/jquery.js\"> </script>\n");
      out.write("  	<script type=\"text/javascript\" src=\"javascript/Home.js\"></script>\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"></script>\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
