/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-06-08 19:30:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.aadhar_management_system.dao.UserDAOImpl;
import com.aadhar_management_system.dto.UserDTO;
import com.aadhar_management_system.service.*;

public final class Profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.aadhar_management_system.service");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.aadhar_management_system.dto.UserDTO");
    _jspx_imports_classes.add("com.aadhar_management_system.dao.UserDAOImpl");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>Profile</title>\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/Profile.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");

		response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
		if(session.getAttribute("userName")== null){
			response.sendRedirect("Home.jsp");
		} else {
		String name = (String) session.getAttribute("userName");
		int role = (int) session.getAttribute("userRole");
		int id = (int) session.getAttribute("id");
		UserService userService = new UserServiceImpl();
     	UserDTO userDTO = new UserDTO();
		userDTO = userService.getUserById(id);
	
      out.write('\n');
      out.write('	');
      out.write(' ');
if (role == 1){ 
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light \"style=\"background-color: #e3f2fd;\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <a class=\"navbar-brand\" href=\"\">AMS</a>\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\"  aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("            </button>\n");
      out.write("            <div class=\"collapse navbar-collapse justify-content\" id=\"navbarNav\">\n");
      out.write("				<ul class=\"navbar-nav\">\n");
      out.write("					<li class=\"nav-item\">\n");
      out.write("					&nbsp;&nbsp;<button id=\"userDetailsButton\" type=\"submit\" data-id=\"selectAllUsers\" class=\"btn btn-primary\">User Details</button>\n");
      out.write("					</li>\n");
      out.write("					<li class=\"nav-item\">\n");
      out.write("					&nbsp;&nbsp;<a class=\"btn btn-primary\" aria-current=\"page\" href=\"");
      out.print(request.getContextPath());
      out.write("/Profile.jsp\">Profile</a>\n");
      out.write("					</li>\n");
      out.write("					<li class=\"nav-item\">\n");
      out.write("                    &nbsp;&nbsp;<button class=\"btn btn-primary\" id=\"addJunior\" data-bs-toggle=\"modal\" data-bs-target=\"#registerJunior\">Add Junior</button>\n");
      out.write("                    </li>\n");
      out.write("					<li class=\"nav-item\">\n");
      out.write("					&nbsp;&nbsp;<button type=\"submit\" id=\"logoutButton\" class=\"btn btn-danger\">Logout</button>\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("       </div>\n");
      out.write("</nav> \n");
      out.write("	<div class=\"text-center\">\n");
      out.write("		<h2 id=\"greet\"> Welcome Administrator: ");
      out.print(name);
      out.write("</h2>\n");
      out.write("	</div>\n");
      out.write("		<div class=\"row justify-content-center\">\n");
      out.write("		<div class=\"col-md-6\">\n");
      out.write("			<div class=\"card mt-5\">\n");
      out.write("				<div class=\"card-header\">\n");
      out.write("					<h3 class=\"text-center\">Update Details</h3>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"card-body\">\n");
      out.write("					<form action=\"#\" method=\"post\" id=\"update\" enctype=\"multipart/form-data\">\n");
      out.write("						<input type=\"hidden\" value=\"update\" name=\"method\">\n");
      out.write("						<input type=\"hidden\" id=\"id1\" name=\"id\" value=\"");
      out.print(id);
      out.write("\">\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\">First Name</label> <input type=\"text\" class=\"form-control\" id=\"firstname\" name=\"fname\" value=\"");
      out.print(userDTO.getFname());
      out.write("\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"lastname\">Last Name</label> \n");
      out.write("							<input type=\"text\" class=\"form-control\" id=\"lastname\" name=\"lname\" value=\"");
      out.print(userDTO.getLname());
      out.write("\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"email\">Email</label> \n");
      out.write("							<input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" value=\"");
      out.print(userDTO.getEmail());
      out.write("\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"dob\">Date Of Birth</label>\n");
      out.write("							<input type=\"date\" class=\"form-control\" id=\"dob\" name=\"dateOfBirth\" value=\"");
      out.print(userDTO.getDateOfBirth());
      out.write("\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"password\">Password</label>\n");
      out.write("							<input type=\"password\" class=\"form-control\" id=\"password\" name=\"pass\" value=\"");
      out.print(userDTO.getPass());
      out.write("\"> \n");
      out.write("							<input type=\"checkbox\" onclick=\"showPassword()\">&nbsp; Show Password\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label>Gender</label>\n");
      out.write("						<br>\n");
      out.write("						<div class=\"form-check form-check-inline\">\n");
      out.write("							<input class=\"form-check-input\" type=\"radio\" name=\"gender\" id=\"male\" value=\"male\" ");
if (userDTO.getGender().equals("male")) {
      out.write(" checked ");
}
      out.write(" required> \n");
      out.write("							<label class=\"form-check-label\" for=\"male\">Male</label>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-check form-check-inline\">\n");
      out.write("							<input class=\"form-check-input\" type=\"radio\" name=\"gender\" id=\"female\" value=\"female\" ");
if (userDTO.getGender().equals("female")) {
      out.write(" checked ");
}
      out.write(" required> \n");
      out.write("							<label class=\"form-check-label\" for=\"female\">Female</label>\n");
      out.write("						</div>\n");
      out.write("						</div>\n");
      out.write("						<div>\n");
      out.write("							<label>Country :</label> <br> <select name=\"country\" style=\"width: 150px\">\n");
      out.write("								<option ");
if (userDTO.getCountry().equals("India")) {
      out.write(" selected=\"selected\" ");
}
      out.write(">India</option>\n");
      out.write("								<option ");
if (userDTO.getCountry().equals("USA")) {
      out.write(" selected=\"selected\" ");
}
      out.write(">USA</option>\n");
      out.write("								<option ");
if (userDTO.getCountry().equals("US")) {
      out.write(" selected=\"selected\" ");
}
      out.write(">US</option>\n");
      out.write("								<option ");
if (userDTO.getCountry().equals("Germany")) {
      out.write(" selected=\"selected\" ");
}
      out.write(">Germany</option>\n");
      out.write("							</select>\n");
      out.write("						</div>\n");
      out.write("						<div>\n");
      out.write("							<input type=\"hidden\" value=\"");
      out.print( userDTO.getRole() );
      out.write("\" name=\"role\">\n");
      out.write("						</div>\n");
      out.write("						<br>\n");
      out.write("						<div>\n");
      out.write("							Select Image :\n");
      out.write("							<input type=\"file\" name=\"image\" id=\"upload_file\" onchange=\"getImagePreview(event)\">\n");
      out.write("							<div id=\"preview\">\n");
      out.write("								<img style=\"width: 90px !important;\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/");
      out.print(userDTO.getImageFileName());
      out.write("\">\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"text-center mt-3\">\n");
      out.write("							<button type=\"submit\" class=\"btn btn-outline-primary\">Update</button>\n");
      out.write("						</div>\n");
      out.write("					</form>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	");

	} else if (role == 2) {
	
      out.write("\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light \"style=\"background-color: #e3f2fd;\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("            <a class=\"navbar-brand\" href=\"\">AMS</a>\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\"\n");
      out.write("                aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("            </button>\n");
      out.write("            <div class=\"collapse navbar-collapse justify-content\" id=\"navbarNav\">\n");
      out.write("                <ul class=\"navbar-nav\">\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("					&nbsp;&nbsp;<button id=\"juniorUserDetailsButton\" type=\"submit\" data-id=\"");
      out.print(id);
      out.write("\" class=\"btn btn-primary\">User Details</button> \n");
      out.write("					</li>\n");
      out.write("					<li class=\"nav-item\">\n");
      out.write("					&nbsp; &nbsp;<a class=\"btn btn-primary\" href=\"");
      out.print(request.getContextPath());
      out.write("/Profile.jsp\">Profile </a>\n");
      out.write("					</li>\n");
      out.write("                    <li class=\"nav-item\">\n");
      out.write("                    &nbsp;&nbsp;<button type=\"submit\" id=\"logoutButton\" class=\"btn btn-danger\">Logout</button>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write(" </nav> \n");
      out.write("	<div class=\"text-center\">\n");
      out.write("		<h2 id=\"greet\"> Welcome Junior: ");
      out.print(name);
      out.write("</h2>\n");
      out.write("	</div>\n");
      out.write("		<div class=\"row justify-content-center\">\n");
      out.write("		<div class=\"col-md-6\">\n");
      out.write("			<div class=\"card mt-5\">\n");
      out.write("				<div class=\"card-header\">\n");
      out.write("					<h3 class=\"text-center\">Update Details</h3>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"card-body\">\n");
      out.write("					<form action=\"#\" method=\"post\" id=\"update\" enctype=\"multipart/form-data\">\n");
      out.write("						<input type=\"hidden\" value=\"update\" name=\"method\">\n");
      out.write("						<input type=\"hidden\" id=\"id1\" name=\"id\" value=\"");
      out.print(id);
      out.write("\">\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"firstname\">First Name</label> <input type=\"text\" class=\"form-control\" id=\"firstname\" name=\"fname\" value=\"");
      out.print(userDTO.getFname());
      out.write("\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"lastname\">Last Name</label> \n");
      out.write("							<input type=\"text\" class=\"form-control\" id=\"lastname\" name=\"lname\" value=\"");
      out.print(userDTO.getLname());
      out.write("\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"email\">Email</label> \n");
      out.write("							<input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" value=\"");
      out.print(userDTO.getEmail());
      out.write("\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"dob\">Date Of Birth</label>\n");
      out.write("							<input type=\"date\" class=\"form-control\" id=\"dob\" name=\"dateOfBirth\" value=\"");
      out.print(userDTO.getDateOfBirth());
      out.write("\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label for=\"password\">Password</label>\n");
      out.write("							<input type=\"password\" class=\"form-control\" id=\"password\" name=\"pass\" value=\"");
      out.print(userDTO.getPass());
      out.write("\"> \n");
      out.write("							<input type=\"checkbox\" onclick=\"showPassword()\">&nbsp; Show Password\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-group\">\n");
      out.write("							<label>Gender</label><br>\n");
      out.write("							<div class=\"form-check form-check-inline\">\n");
      out.write("								<input class=\"form-check-input\" type=\"radio\" name=\"gender\" id=\"male\" value=\"male\"\n");
      out.write("									");
if (userDTO.getGender().equals("male")) {
      out.write(" checked ");
}
      out.write(" required> \n");
      out.write("								<label class=\"form-check-label\" for=\"male\">Male</label>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"form-check form-check-inline\">\n");
      out.write("								<input class=\"form-check-input\" type=\"radio\" name=\"gender\" id=\"female\" value=\"female\"\n");
      out.write("									");
if (userDTO.getGender().equals("female")) {
      out.write(" checked ");
}
      out.write(" required> \n");
      out.write("								<label class=\"form-check-label\" for=\"female\">Female</label>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div>\n");
      out.write("							<label>Country :</label> <br> <select name=\"country\"\n");
      out.write("								style=\"width: 150px\">\n");
      out.write("\n");
      out.write("								<option ");
if (userDTO.getCountry().equals("India")) {
      out.write("\n");
      out.write("									selected=\"selected\" ");
}
      out.write(">India</option>\n");
      out.write("								<option ");
if (userDTO.getCountry().equals("USA")) {
      out.write("\n");
      out.write("									selected=\"selected\" ");
}
      out.write(">USA</option>\n");
      out.write("								<option ");
if (userDTO.getCountry().equals("US")) {
      out.write("\n");
      out.write("									selected=\"selected\" ");
}
      out.write(">US</option>\n");
      out.write("								<option ");
if (userDTO.getCountry().equals("Germany")) {
      out.write("\n");
      out.write("									selected=\"selected\" ");
}
      out.write(">Germany</option>\n");
      out.write("							</select>\n");
      out.write("						</div>\n");
      out.write("						<div>\n");
      out.write("							<input type=\"hidden\" value=\"");
      out.print( userDTO.getRole() );
      out.write("\" name=\"role\">\n");
      out.write("						</div>\n");
      out.write("						<br>\n");
      out.write("						<div>\n");
      out.write("							Select Image :\n");
      out.write("							<input type=\"file\" name=\"image\" id=\"upload_file\" onchange=\"getImagePreview(event)\">\n");
      out.write("							<div id=\"preview\">\n");
      out.write("								<img style=\"width: 90px !important;\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/");
      out.print(userDTO.getImageFileName());
      out.write("\">\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"text-center mt-3\">\n");
      out.write("							<button type=\"submit\" class=\"btn btn-outline-primary\">Update</button>\n");
      out.write("						</div>\n");
      out.write("					</form>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	");
} else { 
      out.write("\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light \"\n");
      out.write("		style=\"background-color: #e3f2fd;\">\n");
      out.write("		<div class=\"container-fluid\">\n");
      out.write("			<a class=\"navbar-brand\" href=\"\">AMS</a>\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("			</button>\n");
      out.write("			<div class=\"collapse navbar-collapse justify-content\" id=\"navbarNav\">\n");
      out.write("				<ul class=\"navbar-nav\">\n");
      out.write("					<li class=\"nav-item\">\n");
      out.write("					&nbsp;&nbsp;<a class=\"btn btn-primary\"  aria-current=\"page\" href=\"");
      out.print(request.getContextPath());
      out.write("/User_documents.jsp\">Upload Documents</a>\n");
      out.write("					</li>\n");
      out.write("					<li class=\"nav-item\">\n");
      out.write("					&nbsp;&nbsp;<a class=\"btn btn-primary\" id=\"profile\" aria-current=\"page\" href=\"");
      out.print(request.getContextPath());
      out.write("/Profile.jsp\">Profile</a>\n");
      out.write("					</li>\n");
      out.write("					<li class=\"nav-item\">\n");
      out.write("					&nbsp;&nbsp;<button type=\"submit\" id=\"logoutButton\" class=\"btn btn-danger\">Logout</button>\n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("	<div class=\"text-center\">\n");
      out.write("		<h2 id=\"greet\"> Welcome User: ");
      out.print(name);
      out.write("</h2>\n");
      out.write("	</div>\n");
      out.write("	<div>\n");
      out.write("	<div class=\"row justify-content-center\">\n");
      out.write("		<div class=\"col-md-4\">\n");
      out.write("			<div class=\"card mt-5\">\n");
      out.write("				<div class=\"card-header\">\n");
      out.write("					<h3 class=\"text-center\">Update Details</h3>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"card-body\">\n");
      out.write("					<form action=\"#\" method=\"POST\" id=\"update\" enctype=\"multipart/form-data\">\n");
      out.write("						<input type=\"hidden\" value=\"update\" name=\"method\">\n");
      out.write("						<input type=\"hidden\" id=\"id1\" name=\"id\" value=\"");
      out.print(id);
      out.write("\">\n");
      out.write("						<label for=\"firstname\">First Name</label> \n");
      out.write("						<input type=\"text\" class=\"form-control\" id=\"firstname\" name=\"fname\" value=\"");
      out.print(userDTO.getFname());
      out.write("\">\n");
      out.write("						<label for=\"lastname\">Last Name</label> \n");
      out.write("						<input type=\"text\" class=\"form-control\" id=\"lastname\" name=\"lname\" value=\"");
      out.print(userDTO.getLname());
      out.write("\">\n");
      out.write("						<label for=\"email\">Email</label> \n");
      out.write("						<input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\" value=\"");
      out.print(userDTO.getEmail());
      out.write("\">\n");
      out.write("						<label for=\"dob\">Date Of Birth</label>\n");
      out.write("						<input type=\"date\" class=\"form-control\" id=\"dob\" name=\"dateOfBirth\" value=\"");
      out.print(userDTO.getDateOfBirth());
      out.write("\">\n");
      out.write("						<label for=\"password\">Password</label>\n");
      out.write("						<input type=\"password\" class=\"form-control\" id=\"password\" name=\"pass\" value=\"");
      out.print(userDTO.getPass());
      out.write("\"> \n");
      out.write("						<input type=\"checkbox\" onclick=\"showPassword()\">&nbsp; Show Password\n");
      out.write("						<br>\n");
      out.write("						<label>Gender</label><br>\n");
      out.write("						<div class=\"form-check form-check-inline\">\n");
      out.write("							<input class=\"form-check-input\" type=\"radio\" name=\"gender\" id=\"male\" value=\"male\"\n");
      out.write("							");
if (userDTO.getGender().equals("male")) {
      out.write(" checked ");
}
      out.write(" required> \n");
      out.write("							<label class=\"form-check-label\" for=\"male\">Male</label>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"form-check form-check-inline\">\n");
      out.write("							<input class=\"form-check-input\" type=\"radio\" name=\"gender\" id=\"female\" value=\"female\"\n");
      out.write("							");
if (userDTO.getGender().equals("female")) {
      out.write(" checked ");
}
      out.write(" required> \n");
      out.write("							<label class=\"form-check-label\" for=\"female\">Female</label>\n");
      out.write("						</div>\n");
      out.write("						<div>\n");
      out.write("							<label>Country :</label> <br> \n");
      out.write("							<select name=\"country\" style=\"width: 150px\">\n");
      out.write("								<option ");
if (userDTO.getCountry().equals("India")) {
      out.write("\n");
      out.write("									selected=\"selected\" ");
}
      out.write(">India</option>\n");
      out.write("								<option ");
if (userDTO.getCountry().equals("USA")) {
      out.write("\n");
      out.write("									selected=\"selected\" ");
}
      out.write(">USA</option>\n");
      out.write("								<option ");
if (userDTO.getCountry().equals("US")) {
      out.write("\n");
      out.write("									selected=\"selected\" ");
}
      out.write(">US</option>\n");
      out.write("								<option ");
if (userDTO.getCountry().equals("Germany")) {
      out.write("\n");
      out.write("									selected=\"selected\" ");
}
      out.write(">Germany</option>\n");
      out.write("							</select>\n");
      out.write("						</div>\n");
      out.write("							<input type=\"hidden\" value=\"");
      out.print( userDTO.getRole() );
      out.write("\" name=\"role\">\n");
      out.write("						<br>\n");
      out.write("						<div>\n");
      out.write("							Select Image :\n");
      out.write("							<input type=\"file\" name=\"image\" id=\"upload_file\" onchange=\"getImagePreview(event)\">\n");
      out.write("							<div id=\"preview\">\n");
      out.write("								<img style=\"width: 90px !important;\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/");
      out.print(userDTO.getImageFileName());
      out.write("\">\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"text-center mt-3\">\n");
      out.write("							<button type=\"submit\" class=\"btn btn-outline-primary\">Update</button>\n");
      out.write("						</div>\n");
      out.write("					</form>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("	");
}
      out.write('\n');
      out.write('	');
}
      out.write("\n");
      out.write("<!-- modal for session timeout -->\n");
      out.write("	<div class=\"modal fade\" id=\"sessionTimeout\" data-bs-backdrop=\"static\" data-bs-keyboard=\"false\" tabindex=\"-1\" aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("			<div class=\"modal-content\" >\n");
      out.write("				<div class=\"modal-header text-center\" >\n");
      out.write("					<h1  class=\"modal-title fs-5\" id=\"staticBackdropLabel\">Session Timeout</h1>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-body\" style=\"text-align :center\">\n");
      out.write("					<p>Your session has timed out due to inactivity, Login Again .</p>\n");
      out.write("					<button class=\"btn btn-primary\" id=\"ok-button\">OK</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<script src=\"javascript/jquery.js\"></script>\n");
      out.write("	<script src=\"javascript/SessionCheck.js\"></script>\n");
      out.write("	<script src=\"javascript/Profile.js\"></script>\n");
      out.write("	<script src=\"javascript/juniorProfile.js\"></script>\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"></script>\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
