/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2024-06-08 19:31:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class User_005fdocuments_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>Upload Documents</title>\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" >\n");
      out.write("<link href=\"css/User_documents.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light \"\n");
      out.write("		style=\"background-color: #e3f2fd;\">\n");
      out.write("		<div class=\"container-fluid\">\n");
      out.write("			<a class=\"navbar-brand\" href=\"\">AMS</a>\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\"	aria-label=\"Toggle navigation\">\n");
      out.write("				<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("			</button>\n");
      out.write("			<div class=\"collapse navbar-collapse justify-content\" id=\"navbarNav\">\n");
      out.write("				<ul class=\"navbar-nav\">\n");
      out.write("					<li class=\"nav-item\">\n");
      out.write("							&nbsp;&nbsp;<button type=\"submit\" name=\"userId\" value=\"\" id=\"docsButton\" class=\"btn btn-primary\">Upload Documents</button>\n");
      out.write("						</li>\n");
      out.write("					<li class=\"nav-item\">\n");
      out.write("					&nbsp;&nbsp;<a class=\"btn btn-primary\" id=\"profile\" aria-current=\"page\" href=\"");
      out.print(request.getContextPath());
      out.write("/Profile.jsp\">Profile</a>\n");
      out.write("						</li>\n");
      out.write("						<li class=\"nav-item\">\n");
      out.write("						<form action=\"#\" method=\"POST\" id=\"logout\"> \n");
      out.write(" 							<input type=\"hidden\" value=\"logout\" name=\"method\"> \n");
      out.write(" 							&nbsp;&nbsp;<button type=\"submit\" id=\"logout\" class=\"btn btn-danger\">Logout</button> \n");
      out.write("						</form> \n");
      out.write("					</li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("		");
response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate"); 
                		if(session.getAttribute("userName")== null){
						response.sendRedirect("Home.jsp"); } else { 
      out.write("\n");
      out.write("<div class=\"row justify-content-center\">\n");
      out.write("	<div class=\"col-md-6\">\n");
      out.write("    <div class=\"card mt-5\">\n");
      out.write("      <div class=\"card\">\n");
      out.write("        <div class=\"card-body\">\n");
      out.write("          <h2 class=\"card-title text-center\">Welcome To AMS</h2>\n");
      out.write("          <h5 class=\"card-text text-center\">There are just a few steps to complete your profile.</h5>\n");
      out.write("          <div class=\"card\" id=\"bcard\">\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("              <form action=\"#\" method=\"POST\" id=\"birth\" enctype=\"multipart/form-data\">\n");
      out.write("                <div id=\"birthContainer\">\n");
      out.write("                  <h3 class=\"btext\">Birth Certificate</h3>\n");
      out.write("                  <div id=\"birthDocument\">\n");
      out.write("                  <input type=\"file\" name=\"document\" id=\"birth_upload_file\" class=\"form-control\" required>\n");
      out.write("                  <button type=\"button\" id=\"birthDoc\" class=\"btn btn-primary mt-2\">Upload</button>\n");
      out.write("				  </div>\n");
      out.write("				  <img style='width: 8% !important; display:none;' id=\"birthSubmit\" src='");
      out.print(request.getContextPath() );
      out.write("/images/submitTick.png'>                  \n");
      out.write("                </div>\n");
      out.write("                <h6>Take a photo or scan your birth certificate.</h6>\n");
      out.write("                  <a href=\"#\" id=\"modalTrigger1\" style='display:none;'>View Document</a>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"card\" id=\"bcard\">\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("              <form action=\"#\" method=\"POST\" id=\"poa\" enctype=\"multipart/form-data\">\n");
      out.write("                <div id=\"birthContainer\">\n");
      out.write("                  <h3>Proof Of Address</h3>\n");
      out.write("                  <div id=\"poaDocument\">\n");
      out.write("                  <input type=\"file\" name=\"document\" id=\"proof_of_address\" class=\"form-control\" required>\n");
      out.write("                  <button type=\"button\" id=\"poaDoc\" class=\"btn btn-primary mt-2\">Upload</button>\n");
      out.write("                  </div>\n");
      out.write("                  <img style='width: 8% !important; display:none;' id=\"poaSubmit\" src='");
      out.print(request.getContextPath() );
      out.write("/images/submitTick.png'>\n");
      out.write("                </div>\n");
      out.write("                <h6>Take a photo or scan your Proof Of Address.</h6>\n");
      out.write("                 <a href=\"#\" id=\"modalTrigger2\" style='display:none;'>View Document</a>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"card\" id=\"bcard\">\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("              <form  action=\"#\" method=\"POST\" id=\"rc\" enctype=\"multipart/form-data\">\n");
      out.write("                <div id=\"birthContainer\">\n");
      out.write("                  <h3 class=\"rcard\">Ration Card</h3>\n");
      out.write("                  <div id=\"rcDocument\">\n");
      out.write("                    <input type=\"file\" name=\"document\" id=\"ration_card\" class=\"form-control\" required>\n");
      out.write("                    <button type=\"button\" id=\"rcDoc\" class=\"btn btn-primary mt-2\">Upload</button>\n");
      out.write("                  </div>\n");
      out.write("                 <img style='width: 8% !important; display:none;' id=\"rcSubmit\" src='");
      out.print(request.getContextPath() );
      out.write("/images/submitTick.png'>\n");
      out.write("                </div>\n");
      out.write("                <h6>Take a photo or scan your Ration Card.</h6>\n");
      out.write("                <a href=\"#\" id=\"modalTrigger3\" style='display:none;'>View Document</a>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"card\" id=\"bcard\">\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("              <form action=\"#\" method=\"POST\" id=\"sign\" enctype=\"multipart/form-data\">\n");
      out.write("                <div id=\"birthContainer\">\n");
      out.write("                  <h3 class=\"stext\">Sign</h3>\n");
      out.write("                  <div id=\"signDocument\"> \n");
      out.write("                    <input type=\"file\" name=\"document\" id=\"sign\" class=\"form-control\" required>\n");
      out.write("                    <button type=\"button\" id=\"sdoc\" class=\"btn btn-primary mt-2\">Upload</button>\n");
      out.write("                  </div>\n");
      out.write("                 <img style='width: 8% !important; display:none;' id=\"signSubmit\" src='");
      out.print(request.getContextPath() );
      out.write("/images/submitTick.png'>\n");
      out.write("                </div>\n");
      out.write("                <h6>Take a photo or scan your sign.</h6>\n");
      out.write("                <a href=\"#\" id=\"modalTrigger4\" style='display:none;'>View Document</a>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div> \n");
      out.write(" ");
}
      out.write(" \n");
      out.write("<div class=\"modal fade \" id=\"ModalForDoc\" tabindex=\"-1\" aria-labelledby=\"\" aria-hidden=\"true\">\n");
      out.write("  <div class=\"modal-dialog modal-xl\">\n");
      out.write("    <div class=\"modal-content\" style=\"height:700px;\">\n");
      out.write("      <div class=\"modal-header\">\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">View Documents</h5>\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("              <iframe id=\"modalIframe\" width=\"100%\" height=\"100%\" ></iframe>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-footer\">\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\">Save changes</button>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div> \n");
      out.write("\n");
      out.write("<!-- modal for session timeout -->\n");
      out.write("	<div class=\"modal fade\" id=\"sessionTimeout\" data-bs-backdrop=\"static\" data-bs-keyboard=\"false\" tabindex=\"-1\" aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("			<div class=\"modal-content\" >\n");
      out.write("				<div class=\"modal-header text-center\" >\n");
      out.write("					<h1  class=\"modal-title fs-5\" id=\"staticBackdropLabel\">Session Timeout</h1>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-body\" style=\"text-align :center\">\n");
      out.write("					<p>Your session has timed out due to inactivity, Login Again .</p>\n");
      out.write("					<button class=\"btn btn-primary\" id=\"ok-button\">OK</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("<script type=\"text/javascript\">var contextPath = '");
      out.print(request.getContextPath());
      out.write("' </script>\n");
      out.write("<script src=\"javascript/jquery.js\"></script>\n");
      out.write("<script src=\"javascript/SessionCheck.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" ></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"></script>\n");
      out.write("<script src=\"javascript/User_documents.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
